# Generated by Django 5.0.3 on 2024-03-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seminar_2', '0003_games_remove_post_author_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='site',
            new_name='side',
        ),
    ]
