# Generated by Django 5.0.3 on 2024-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seminar_2', '0004_rename_site_games_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField(max_length=1500)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
